pages/index.js
schemas/schema.js

Replaced single page form with multi page one for submission. However a minor bug was introduced causing the SDG subform to shift to top of page and persists even on navigating to page 2.

Replaced single page form with multi page one for submission

---

schemas/schema.js

Populated `license` dropdown with entire OSI list.

Populated license dropdown with entire OSI list

---

schemas/schema.js

Add indicators 7 & 8 to data driven submission form: updated schema & pull request

Add indicators 7 to 9 to submission form

---

pages/index.js
schemas/schema.js

Added contact information to `schema`.

Added contact information to schema

---

README.md
pages/api/openPR.js
pages/index.js
schemas/schema.js

Moving the `openPR()` functionality to a server-side api to securely handle environment variables. Addition to README documents configuration of needed environment variables.

BLD: api for openPR

---

schemas/schema.js

The DPG google form validates email address, so I thought we might add it here as well. I directly used the code given [here](https://data-driven-forms.org/)

Add Email validator

---

.github/workflows/main.yml
.prettierignore
components/footerComponent.js
package-lock.json
package.json
pages/_app.js
pages/_document.js
pages/api/loadDB/[uuid].js
pages/api/openPR.js
pages/api/removeDB/[uuid].js
pages/api/saveDB/[uuid].js
pages/error.js
pages/form.js
pages/index.js
pages/legal.js
pages/thank-you.js
schemas/schema.js
src/theme.js

Re-implements #16 to avoid solving individual file conflicts after merging the massive #13
[Initial tests](https://github.com/lacabra/publicgoods-candidates/pull/9) seem to show that functionality remains the same.

BLD: add ESlint + Prettier + Husky + CI

---

schemas/schema.js

Converted `documentationURL` & `evidenceStandardSupport` into arrays using `fieldArray` component

Converted documentationURL & evidenceStandardSupport into FieldArrays 

---

package.json

- Updated the `package.json` file to include NodeJS v12

updated engine tag

---

pages/api/openPR.js
pages/form.js
pages/thank-you.js
schemas/schema.js

Required questions did not have the star (*) visual cue.
They were missing the `isRequired: true,` property in JSX.
They have been added now.

DPG form visual cues added for required questions

---

pages/api/openPR.js

fixes [#607](https://github.com/unicef/publicgoods-candidates/issues/607)

BUGFIX: Fixes Invalid Branch Names Auto-generated by Online Form

---

schemas/schema.js

Updated the country lists to include Egypt in the dropdowns

Updated country list

---

schemas/schema.js

This PR
- Updated question with clearer instruction
- Fixes issue [67](https://github.com/DPGAlliance/DPG-Standard/issues/67)

Minor-Fix: Form Suggestion-SDG Question

---

next.config.js

This PR:
- fixes unicef/publicgoods-scripts#33

Enable CORS from Eligibility Form

---

CODE_OF_CONDUCT.md
LICENSE
README.md

Added Apache License 2.0 and Contributor Covenant Code of Conduct

MAINT: add LICENSE, CODE_OF_CONDUCT

---

next.config.js

This PR:
- Addresses #41 after further tests, using this [Vercel post](https://vercel.com/support/articles/how-to-enable-cors#enabling-cors-in-a-next.js-app) as a reference

BUG: updated CORS Header value

---

pages/api/saveDB/[uuid].js

This works towards fixing unicef/publicgoods-scripts#49, which now works on my local dev environment. Need to push this to production to continue troubleshooting
Cc: @nathanfletcher, @rachita19082

BUG: handle OPTIONS to allow CORS

---

schemas/schema.js

Fix DPGAlliance/DPG-Standard#82

MAINT: fix typo in acronyms

---

pages/form.js

This PR
- Fixes #56 
- Removes null values from arrays in the submission before it is committed via `saveToDb`

recursively going through submission and removing nulls

---

schemas/schema.js

This PR Fixes #46 
- The form question, in particular, has been formatted properly.
- 
- There was a bug in how the questions were displayed, in that some conditional questions were not showing up at all
- Those conditional questions have been fixed according to the schema

BUG:  conditional statements for PII section

---

package-lock.json
package.json
pages/api/openPR.js
pages/form.js

This PR fixes #78 
The `removeNullsInArrays` function ran to check and remove `null` values introduced by the user as the form was being filled.
This check affected the dynamic `field-array` question types of the submission form by removing naturally occurring empty array fields as soon as they were clicked on which made it difficult to fill questions like:
- Standards list (Please supply either text or URLs)
- Principles and best practices
This null check process was moved to run right before submission
NPM packages for `data-driven-forms` and react were updated to `3.15.7` and `17.0.2` respectively.

BUGFIX: field-array question types not accepting input

---

schemas/schema.js

Updated to dot notation for standards.implementBestPractices

PATCH: updated schema implementBestPractices

---

schemas/schema.js

This PR fixes #88 
The regex has been updated to `^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$`
It can be tested on the fly at https://regexr.com/3e48o

BUGFIX: Updated email validation regex

---

schemas/schema.js

- Update schema to support multiple software repositories

Modify the submission form to change the corresponding interface to allow for inputting multiple repositoryURL

---

pages/api/openPR.js

Remove obsolete `repositoryURL` keys - replace with repositories

Remove obsolete repositoryURL keys 

---

schemas/schema.js

Added OGL-UK-3.0 (Open Government Licence) to form

Added OGL-UK-3.0 license to form

---

components/footerComponent.js

- Remove contact info - info@digitalpublicgoods.net

Update Footer component

---

pages/form.js
pages/index.js

Provide redirection link to webApp 2.0

Enable redirection to webApp 2.0
